#podman build -f src/main/container/Containerfile -t apps-spring .
FROM registry.access.redhat.com/ubi8/openjdk-8:1.16-1.1687182685

USER root

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*.jar /work

EXPOSE 8888
USER 1001

CMD ["java", "-jar", "crud-1.0.0.jar"]